// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const DB_HOST = process.env["DB_HOST"] || "localhost";
const DB_PORT = process.env["DB_PORT"] || "5432";
const DB_NAME = process.env["DB_NAME"] || "social_feed";
const DB_USER = process.env["DB_USER"] || "postgres";
const DB_PASSWORD = process.env["DB_PASSWORD"] || "postgres";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: `postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?schema=public`,
  },
});
